### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aguspriy** [haxpax/gosms#14]
On Ubuntu:
$ go get github.com/haxpax/gosms
$ cd $GOPATH/src/github.com/haxpax/gosms/dashboard
$ go get
error :
# github.com/haxpax/gosms/dashboard
./server.go:71:20: multiple-value uuid.NewV1() in single-value context
$ go build

Solutions to issue please, 
Running in local.

Thx.

**Comment by FeyDo** [comment]
please change in server.go line 71 to be 👍 

	uuid := uuid.Must(uuid.NewV1())
	fmt.Printf("UUIDv1: %s\n", uuid)

**Comment by FeyDo** [comment]
it works for me

**Comment by aguspriy** [comment]
Ok iam try and succes to run "go get"
So to running app there must be a modem?
so sorry, i beginer in go.

**Comment by aguspriy** [comment]
Hay FeyDO...

error:
Invalid config:  Fatal: DEVICE0 DEVID is not set  Aborting
