### ISSUE TITLE
multiple-value uuid.NewV1() in single-value context

### ISSUE THREAD

**Issue by charlieuk2k** [haxpax/gosms#17]
Issue when building with go build.

Issue in server.go, line 71. Output: multiple-value uuid.NewV1() in single-value context

changed line 71 from uuid := uuid.NewV1() to uuid,_ := uuid.NewV1()

go build is successful with modification. Able to execute binary.

Believe this is due to update of go.uuid, ref: https://github.com/hlandau/acme/issues/293

**Comment by Omie** [comment]
thanks for the update, PR is welcome but if not, I'll put in fix when I'll get some time :)

**Comment by batara666** [comment]
since 2018 ?

**Comment by Omie** [comment]
can't help, we sort of moved on after getting different jobs, different cities etc. thanks for the fix.
