### ISSUE TITLE
No interface

### ISSUE THREAD

**Issue by ElAmen** [haxpax/gosms#18]
Please after running dashboard.exe I only get a brief command line windows an the nothing. Kindly help.
Thanks

**Comment by Omie** [comment]
you should execute dashboard.exe which runs an http server. Once it's up, open a browser and navigate to http://localhost:8951/

**Comment by ElAmen** [comment]
Invalid config:  Fatal: DEVICE0 COMPORT is not set  Aborting
Please when I run dashboard I get this error.

**Comment by Omie** [comment]
Please read the documentation in readme and `dashboard/conf.ini`. All the instructions are given. In case of this one, you have not configured any device to use as a modem.
