### ISSUE TITLE
API request example?

### ISSUE THREAD

**Issue by demogorgonz** [haxpax/gosms#4]
Can someone please provide examples for API usage :) ?

Thank you!

**Comment by Omie** [comment]
hey,

API specification is quite clear I suppose, please let me know what wasn't clear enough so that I can update the document as well.

As for example, this is how one can push an sms using requests module in Python

```

#pip install requests
import requests

sms = { "mobile": "+919890098900", "message": "hello, world" }
r = requests.post("http://<gosms-server-ip>:8951/api/sms/", data=msg)
print r.text

```

**Comment by demogorgonz** [comment]
@Omie there is no web API i suppose ? It would be great if parameters could be forwarded in URL string, for example :
"http://localhost/mobile=+xxxxxxxxx%message=hello, world"

**Comment by Omie** [comment]
@demogorgonz It is a web API :) We are using POST instead of GET since it makes more sense.

**Comment by demogorgonz** [comment]
@Omie i thought it would be neat feature that API could listen via web URL, something like rundeck does :+1: 

Anyway, thank you very much!
