### ISSUE TITLE
Support for MMS?

### ISSUE THREAD

**Issue by StabbyCutyou** [haxpax/gosms#5]
I didn't see it called out in the readme, but is there any (or any plans for) support for MMS?

**Comment by Omie** [comment]
Hey! haven't really thought of it yet. Actually if we just get that use-android-phone-to-send-sms part done then this would be easily doable.
but I am too much caught up to spend some time on this. Sorry :(

**Comment by StabbyCutyou** [comment]
Not a problem at all! If I knew anything about MMS I'd try to add the
feature in myself... but if I knew anything about MMS I wouldn't need to
ask about feature support in other people libraries, either lol.

Thanks for the reply!
